module.exports = {
	endOfLine: "lf",
	semi: true,
	singleQuote: false,
	trailingComma: "es5",
	tabWidth: 3,
	useTabs: true,
	plugins: ["@ianvs/prettier-plugin-sort-imports"],
	importOrder: [
		"^(react/(.*)$)|^(react$)",
		"",
		"^(next/(.*)$)|^(next$)",
		"",
		"<THIRD_PARTY_MODULES>",
		"",
		"^types$",
		"^@/types/(.*)$",
		"^@/config/(.*)$",
		"",
		"^@/client/(.*)$",
		"",
		"^[./]",
	],
	importOrderSeparation: false,
	importOrderSortSpecifiers: true,
	importOrderBuiltinModulesToTop: true,
	importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
	importOrderMergeDuplicateImports: true,
	importOrderCombineTypeAndValueImports: true,
};
